### ISSUE TITLE
`plugin-window-events` seems to be firing twice

### ISSUE THREAD

**Issue by kostas-pblworks** [appsignal/appsignal-javascript#627]
**Describe the bug**
When using the `plugin-window-events` and an error is being thrown, two requests with the same datetime are being sent to the server.

**To Reproduce**

The example below will record two errors in AppSignal dashboard

```JS
// ...
useEffect(() => {
    appsignal.addDecorator((span) => {
      return span
    })
    appsignal.use(plugin({}))
  }, [])
// ...


return (
  <button
    onClick={async () => {
       new Promise((resolve, reject) => {
          reject('fail')
       })
    }}
  />
)

```

**Expected behavior**
Only one error should be recorded

**Additional context**
Btw, the errors in AppSignal don't have any stacktrace. Is that expected?

**Comment by unflxw** [comment]
Hi @kostas-pblworks!

I have not been able to reproduce the issue by using the plugin directly, without React. I believe what is likely happening is that this React component is being rendered more than once, triggering the `useEffect` block several times, which would add the plugin several times and as such add several event handlers, each of which would report the same error.

Do not add AppSignal plugins within an `useEffect` block. Instead, use `appsignal.use()` and `appsignal.addDecorator()` at the point in your codebase where you initialise AppSignal (which should itself not be a React component!)

**Comment by unflxw** [comment]
Specifically, it's possible that you're using [`<StrictMode>`](https://react.dev/reference/react/StrictMode#reference), which re-renders components twice intentionally, and runs their effects twice, in order to help you spot issues with effect cleanup.

AppSignal plugins are not meant to be initialised within effects.

**Comment by kostas-pblworks** [comment]
Thank you @unflxw , because I'm working with Nextjs and there isn't one single entry point of initialization, I've ended up doing something like that:

```
...
const render = useRef(false)

  useEffect(() => {
    if (!render.current) {
      render.current = true
      appsignal.addDecorator((span) => {
        if (session.session?.user.id) {
          return span.setTags({ user_id: session.session.user.id })
        }
        return span
      })
      appsignal.use(plugin({}))
    }
  }, [])

```

which works just fine. Btw consider create an addition to the library to not add the same plugin a second time.

Also, did you saw my comment above about the stacktrace missing? do you have any idea maybe why?

Thank you

**Comment by unflxw** [comment]
Hi @kostas-pblworks! I'm glad you found a solution. I'm no Next.js expert, so take this with a grain of salt, but you might also want to consider [using `@next/script`'s inline scripts](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts#inline-scripts).

> Btw consider create an addition to the library to not add the same plugin a second time.

Thank you for the suggestion. That makes sense, I will look into it.

> Also, did you saw my comment above about the stacktrace missing? do you have any idea maybe why?

Sorry, I did miss that the first time around! Thanks for bringing it to my attention. I'll take a look and get back to you on that as well. I think it might be due to the unusual nature of the `window.onerror` handler, but I'll see if there's something that can be done to improve on this.

**Comment by unflxw** [comment]
Hi @kostas-pblworks! Could you share with us over at support@appsignal.com an example of an error sample that does not contain a stacktrace? I am not able to produce one myself. Please include a link to this GitHub issue in the email.

**Comment by unflxw** [comment]
Clarified over support the (expected) circumstances under which some promise rejections do not have stacktraces.
